### ISSUE TITLE
Not able to run example data with most of the algorithm

### ISSUE THREAD

**Issue by Hsu-Che-Wei** [Murali-group/Beeline#42]
Hello,

I followed your instructions and have successfully installed BEELINE. Yet when I run `python BLRunner.py --config config-files/config.yaml`, only two algorithm, PIDC and GRNVBEM are successfully run. The others have error messages such as:

`(BEELINE) raphael830102@beeline-cwh:~/Beeline$ python BLRunner.py --config=config-files/new_config.yaml 
Skipping PIDC
Skipping GRNVBEM
Skipping GRNBOOST2
Skipping PPCOR
Skipping SCODE
Skipping SCNS
Skipping LEAP
Skipping GRISLI
Skipping SINGE
Skipping SCRIBE
<BLRun.BLRun object at 0x7f29f320a080>
Evaluation started
docker run --rm -v /home/raphael830102/Beeline:/data/ --expose=41269 arboreto:base /bin/sh -c "time -v -o data/outputs/example/GSD/GENIE3/time.txt python runArboreto.py --algo=GENIE3 --inFile=data/inputs/example/G
SD/GENIE3/ExpressionData.csv --outFile=data/outputs/example/GSD/GENIE3/outFile.txt "
Traceback (most recent call last):
  File "runArboreto.py", line 43, in <module>
    main(sys.argv)
  File "runArboreto.py", line 32, in main
    network = genie3(inDF, client_or_address = client)
  File "/opt/conda/lib/python3.7/site-packages/arboreto/algo.py", line 73, in genie3
    limit=limit, seed=seed, verbose=verbose)
  File "/opt/conda/lib/python3.7/site-packages/arboreto/algo.py", line 115, in diy
    expression_matrix, gene_names, tf_names = _prepare_input(expression_data, gene_names, tf_names)
  File "/opt/conda/lib/python3.7/site-packages/arboreto/algo.py", line 214, in _prepare_input
    expression_matrix = expression_data.as_matrix()
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/generic.py", line 5130, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'as_matrix'
docker run --rm -v /home/raphael830102/Beeline:/SINCERITIES/data/ sincerities:base /bin/sh -c "time -v -o data/outputs/example/GSD/SINCERITIES/time0.txt Rscript MAIN.R data/inputs/example/GSD/SINCERITIES/Expressio
nData0.csv data/outputs/example/GSD/SINCERITIES/outFile0.txt "
Loading required package: SuppDists
Loading required package: Matrix
Loaded glmnet 4.0-2
Loading required package: MASS
[1] "data/inputs/example/GSD/SINCERITIES/ExpressionData0.csv"
[2] "data/outputs/example/GSD/SINCERITIES/outFile0.txt"      
Error in coef.cv.glmnet(CV_results, s = "lambda.min") : 
  could not find function "coef.cv.glmnet"
Calls: SINCERITITES
In addition: There were 21 warnings (use warnings() to see them)
Execution halted
docker run --rm -v /home/raphael830102/Beeline:/SINCERITIES/data/ sincerities:base /bin/sh -c "time -v -o data/outputs/example/GSD/SINCERITIES/time1.txt Rscript MAIN.R data/inputs/example/GSD/SINCERITIES/Expressio
nData1.csv data/outputs/example/GSD/SINCERITIES/outFile1.txt "
Loading required package: SuppDists
Loading required package: Matrix
Loaded glmnet 4.0-2
Loading required package: MASS
[1] "data/inputs/example/GSD/SINCERITIES/ExpressionData1.csv"
[2] "data/outputs/example/GSD/SINCERITIES/outFile1.txt"      
Error in coef.cv.glmnet(CV_results, s = "lambda.min") : 
  could not find function "coef.cv.glmnet"
Calls: SINCERITITES
In addition: There were 21 warnings (use warnings() to see them)
Execution halted
Traceback (most recent call last):
  File "BLRunner.py", line 77, in <module>
    main()
  File "BLRunner.py", line 71, in main
    evaluation.runners[idx].parseOutput()
  File "/home/raphael830102/Beeline/BLRun/runner.py", line 90, in parseOutput
    OutputParser[self.name](self)
  File "/home/raphael830102/Beeline/BLRun/genie3Runner.py", line 60, in parseOutput
    OutDF = pd.read_csv(outDir+'outFile.txt', sep = '\t', header = 0)
  File "/home/raphael830102/anaconda3/envs/BEELINE/lib/python3.7/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/raphael830102/anaconda3/envs/BEELINE/lib/python3.7/site-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/raphael830102/anaconda3/envs/BEELINE/lib/python3.7/site-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/home/raphael830102/anaconda3/envs/BEELINE/lib/python3.7/site-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/raphael830102/anaconda3/envs/BEELINE/lib/python3.7/site-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'outputs/example/GSD/GENIE3/outFile.txt' does not exist` 

I wonder if I have missed out any critical step, would be nice if you would provide some suggestions.
Thanks a lot.

**Comment by Hsu-Che-Wei** [comment]
For your convenience, here is the screen shot of the error message.
<img width="1792" alt="Screenshot 2020-09-22 at 11 45 19" src="https://user-images.githubusercontent.com/44936028/93867337-31a8e600-fcc9-11ea-8eaf-73bd6ef6624d.png">

**Comment by adyprat** [comment]
Hey, 
Sorry for the late reply. The GENIE3 and GRNBoost2 errors are because of an issue with Arboreto as discussed here: https://github.com/Murali-group/Beeline/issues/37. I updated the files to fix that issue now. 

Looks like most of the SINCERITIES fails due to a recent update to glmnet to 4.0, I fixed this by downgrading it to 3.0 (used at the time of publication). I cannot seem to figure out what the other issues are from your error message. Please update your Dockers and let me know if you still have issues.
Thanks,
-Aditya

**Comment by Hsu-Che-Wei** [comment]
Hello Aditya,

Thanks for the update! I have reinstalled BEELINE, but ran into this Error, seems to do with Aboreto again.  
<img width="1792" alt="Screenshot 2020-10-05 at 14 50 24" src="https://user-images.githubusercontent.com/44936028/95082884-063be780-071c-11eb-972e-330c25eb6f63.png">

Do you have any ideas what could cause this?

Thank you!
-Che-Wei

**Comment by adyprat** [comment]
Hi,
Looks like it is some Arboreto related issue (see [here](https://github.com/tmoerman/arboreto/issues/7)). I did not encounter this issue when I ran it with the new Docker setup yesterday. Perhaps I will need more information than just that error. What OS are you trying to run this on? 

Anyway, form what I see it should still run the algorithms and produce an output using a different setup internally. Was there no output produced? Can you check in your outputs/example/GSD/GENIE3 or GRNBOOSE2 to see if there's a rankedEdges.csv or an outFile.txt? 
Best,
Aditya

**Comment by Hsu-Che-Wei** [comment]
Hello,

After reinstall Docker and Anaconda and Beeline from scratch, now it works. All 12 algorithms can be successfully run on the example data.

Thanks a lot.

Best,
Che-Wei
