### ISSUE TITLE
Fail to run the code

### ISSUE THREAD

**Issue by yarkable** [Murali-group/Beeline#60]
Hi, thanks for your framework. But I have some trouble running it, could you please kindly solve this problem?  Thank you very much.

My machine: 

CentOS 7, python3.8.8(anaconda)

I've set up my conda env and pulled the docker images locally. As follows:

```
REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
docker.io/nginx                     latest              605c77e624dd        9 days ago          141 MB
docker.io/ubuntu                    18.04               5a214d77f5d7        3 months ago        63.1 MB
docker.io/grnbeeline/singe          0.4.1               3c490a7a05a0        11 months ago       6.53 GB
docker.io/grnbeeline/grisli         base                d9a7a5bd667a        11 months ago       4.96 GB
docker.io/grnbeeline/grnvbem        base                9d23252e9a29        11 months ago       4.9 GB
docker.io/grnbeeline/arboreto       base                c121236d3d3a        15 months ago       4.44 GB
docker.io/grnbeeline/sincerities    base                a75fd007f286        2 years ago         700 MB
docker.io/grnbeeline/scinge         base                d3c3fbf108dc        2 years ago         4.85 GB
docker.io/grnbeeline/ppcor          base                090423078911        2 years ago         686 MB
docker.io/grnbeeline/pidc           base                353eae2c8680        2 years ago         1.97 GB
docker.io/grnbeeline/leap           base                b2a83f050b1b        2 years ago         686 MB
docker.io/grnbeeline/scns           base                42f47737652f        2 years ago         1.02 GB
docker.io/julia                     1.1.0-stretch       e8ea32cc4fbf        2 years ago         450 MB
docker.io/r-base                    3.5.3               62c848eeb175        2 years ago         649 MB
docker.io/meval/scns                latest              38df836f03ef        2 years ago         995 MB
docker.io/continuumio/anaconda3     2018.12             69acfdf1121f        3 years ago         3.72 GB
docker.io/amarburg/matlab-runtime   R2018a              1c030b45e867        3 years ago         3.99 GB

```

I run the command

```
python BLRunner.py --config config-files/config.yaml

```

but the output is:
```
Skipping SCNS
<BLRun.BLRun object at 0x7f2f6f10d0a0>
Evaluation started
Input folder for PIDC does not exist, creating input folder...
Input folder for GRNVBEM does not exist, creating input folder...
Input folder for GENIE3 does not exist, creating input folder...
Input folder for GRNBOOST2 does not exist, creating input folder...
Input folder for PPCOR does not exist, creating input folder...
Input folder for SINCERITIES does not exist, creating input folder...
Input folder for LEAP does not exist, creating input folder...
Input folder for GRISLI does not exist, creating input folder...
Input folder for SINGE does not exist, creating input folder...
docker run --rm -v /home/lzr/Beeline:/data grnbeeline/pidc:base /bin/sh -c "time -v -o data/outputs/example/GSD/PIDC/time.txt julia runPIDC.jl data/inputs/example/GSD/PIDC/ExpressionData.csv data/outputs/example/GSD/PIDC/outFile.txt "
time: data/outputs/example/GSD/PIDC/time.txt: Permission denied
docker run --rm -v /home/lzr/Beeline:/VBEM/data/ grnbeeline/grnvbem:base /bin/sh -c "time -v -o data/outputs/example/GSD/GRNVBEM/time0.txt ./GRNVBEM data/inputs/example/GSD/GRNVBEM/ExpressionData0.csv data/outputs/example/GSD/GRNVBEM/outFile0.txt "
time: data/outputs/example/GSD/GRNVBEM/time0.txt: Permission denied
docker run --rm -v /home/lzr/Beeline:/VBEM/data/ grnbeeline/grnvbem:base /bin/sh -c "time -v -o data/outputs/example/GSD/GRNVBEM/time1.txt ./GRNVBEM data/inputs/example/GSD/GRNVBEM/ExpressionData1.csv data/outputs/example/GSD/GRNVBEM/outFile1.txt "
time: data/outputs/example/GSD/GRNVBEM/time1.txt: Permission denied
docker run --rm -v /home/lzr/Beeline:/data/ --expose=41269 grnbeeline/arboreto:base /bin/sh -c "time -v -o data/outputs/example/GSD/GENIE3/time.txt python runArboreto.py --algo=GENIE3 --inFile=data/inputs/example/GSD/GENIE3/ExpressionData.csv --outFile=data/outputs/example/GSD/GENIE3/outFile.txt "
time: data/outputs/example/GSD/GENIE3/time.txt: Permission denied
docker run --rm -v /home/lzr/Beeline:/data/ --expose=41269 grnbeeline/arboreto:base /bin/sh -c "time -v -o data/outputs/example/GSD/GRNBOOST2/time.txt python runArboreto.py --algo=GRNBoost2 --inFile=data/inputs/example/GSD/GRNBOOST2/ExpressionData.csv --outFile=data/outputs/example/GSD/GRNBOOST2/outFile.txt "
time: data/outputs/example/GSD/GRNBOOST2/time.txt: Permission denied
docker run --rm -v /home/lzr/Beeline:/data/ grnbeeline/ppcor:base /bin/sh -c "time -v -o data/outputs/example/GSD/PPCOR/time.txt Rscript runPPCOR.R data/inputs/example/GSD/PPCOR/ExpressionData.csv data/outputs/example/GSD/PPCOR/outFile.txt "
time: data/outputs/example/GSD/PPCOR/time.txt: Permission denied
docker run --rm -v /home/lzr/Beeline:/SINCERITIES/data/ grnbeeline/sincerities:base /bin/sh -c "time -v -o data/outputs/example/GSD/SINCERITIES/time0.txt Rscript MAIN.R data/inputs/example/GSD/SINCERITIES/ExpressionData0.csv data/outputs/example/GSD/SINCERITIES/outFile0.txt "
time: data/outputs/example/GSD/SINCERITIES/time0.txt: Permission denied
docker run --rm -v /home/lzr/Beeline:/SINCERITIES/data/ grnbeeline/sincerities:base /bin/sh -c "time -v -o data/outputs/example/GSD/SINCERITIES/time1.txt Rscript MAIN.R data/inputs/example/GSD/SINCERITIES/ExpressionData1.csv data/outputs/example/GSD/SINCERITIES/outFile1.txt "
time: data/outputs/example/GSD/SINCERITIES/time1.txt: Permission denied
docker run --rm -v /home/lzr/Beeline:/data/ grnbeeline/leap:base /bin/sh -c "time -v -o data/outputs/example/GSD/LEAP/time0.txt Rscript runLeap.R data/inputs/example/GSD/LEAP/ExpressionData0.csv 0.33 data/outputs/example/GSD/LEAP/outFile0.txt "
time: data/outputs/example/GSD/LEAP/time0.txt: Permission denied
docker run --rm -v /home/lzr/Beeline:/data/ grnbeeline/leap:base /bin/sh -c "time -v -o data/outputs/example/GSD/LEAP/time1.txt Rscript runLeap.R data/inputs/example/GSD/LEAP/ExpressionData1.csv 0.33 data/outputs/example/GSD/LEAP/outFile1.txt "
time: data/outputs/example/GSD/LEAP/time1.txt: Permission denied
docker run --rm -v /home/lzr/Beeline:/runGRISLI/data/ grnbeeline/grisli:base /bin/sh -c "time -v -o data/outputs/example/GSD/GRISLI/time0.txt ./GRISLI  data/inputs/example/GSD/GRISLI/0/ data/outputs/example/GSD/GRISLI/0/outFile.txt 10 3000 0.0 "
time: data/outputs/example/GSD/GRISLI/time0.txt: Permission denied
docker run --rm -v /home/lzr/Beeline:/runGRISLI/data/ grnbeeline/grisli:base /bin/sh -c "time -v -o data/outputs/example/GSD/GRISLI/time1.txt ./GRISLI  data/inputs/example/GSD/GRISLI/1/ data/outputs/example/GSD/GRISLI/1/outFile.txt 10 3000 0.0 "
time: data/outputs/example/GSD/GRISLI/time1.txt: Permission denied
docker run --rm --entrypoint /bin/sh -v /home/lzr/Beeline:/usr/local/SINGE/data/ grnbeeline/singe:0.4.1 -c "echo \" --lambda 0.01 --dT 15 --num-lags 5 --kernel-width 0.5 --prob-zero-removal 0 --prob-remove-samples 0.0 --family gaussian --replicate 0 --ID 0
--lambda 0.01 --dT 15 --num-lags 5 --kernel-width 0.5 --prob-zero-removal 0 --prob-remove-samples 0.0 --family gaussian --replicate 1 --ID 1
--lambda 0.01 --dT 15 --num-lags 5 --kernel-width 0.5 --prob-zero-removal 0 --prob-remove-samples 0.0 --family gaussian --replicate 2 --ID 2
--lambda 0.01 --dT 15 --num-lags 5 --kernel-width 0.5 --prob-zero-removal 0 --prob-remove-samples 0.0 --family gaussian --replicate 3 --ID 3
--lambda 0.01 --dT 15 --num-lags 5 --kernel-width 0.5 --prob-zero-removal 0 --prob-remove-samples 0.0 --family gaussian --replicate 4 --ID 4
--lambda 0.01 --dT 15 --num-lags 5 --kernel-width 0.5 --prob-zero-removal 0 --prob-remove-samples 0.0 --family gaussian --replicate 5 --ID 5 \" > data/inputs/example/GSD/SINGE/hyperparameters.txt && ln -s data/outputs/example/GSD/SINGE/0/ out0 && octave -q --eval \"CSV = csvread('data/inputs/example/GSD/SINGE/ExpressionData0.csv'); X = sparse(CSV(2:end,1:end-1).'); ptime = CSV(2:end,end).'; Kp2.Kp = single(ptime); Kp2.sumKp = single(ptime*X.'); fullKp(1, 75) = Kp2; save('-v7','data/inputs/example/GSD/SINGE/ExpressionData0.mat', 'X', 'ptime', 'fullKp'); f = fopen('data/inputs/example/GSD/SINGE/ExpressionData0.csv'); gene_list = strsplit(fgetl(f), ',')(1:end-1).'; fclose(f); save('-v7','data/inputs/example/GSD/SINGE/GeneList0.mat', 'gene_list')\" && time -v -o data/outputs/example/GSD/SINGE/time0.txt /usr/local/SINGE/SINGE.sh /usr/local/MATLAB/MATLAB_Runtime/v94 standalone data/inputs/example/GSD/SINGE/ExpressionData0.mat data/inputs/example/GSD/SINGE/GeneList0.mat out0 data/inputs/example/GSD/SINGE/hyperparameters.txt "
        Parameters: lambda: 0.01, dT: 15, num_lags: 5, kernel_width: 0.5, prob_zero_removal: 0, prob_remove_samples: 0.0, family: gaussian
/bin/sh: 1: cannot create data/inputs/example/GSD/SINGE/hyperparameters.txt: Permission denied
Traceback (most recent call last):
  File "BLRunner.py", line 77, in <module>
    main()
  File "BLRunner.py", line 68, in main
    evaluation.runners[idx].run()
  File "/home/lzr/Beeline/BLRun/runner.py", line 86, in run
    AlgorithmMapper[self.name](self)
  File "/home/lzr/Beeline/BLRun/singeRunner.py", line 119, in run
    subprocess.check_call(cmdToRun, shell=True)
  File "/home/lzr/anaconda3/envs/mmdet/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'docker run --rm --entrypoint /bin/sh -v /home/lzr/Beeline:/usr/local/SINGE/data/ grnbeeline/singe:0.4.1 -c "echo \" --lambda 0.01 --dT 15 --num-lags 5 --kernel-width 0.5 --prob-zero-removal 0 --prob-remove-samples 0.0 --family gaussian --replicate 0 --ID 0
--lambda 0.01 --dT 15 --num-lags 5 --kernel-width 0.5 --prob-zero-removal 0 --prob-remove-samples 0.0 --family gaussian --replicate 1 --ID 1
--lambda 0.01 --dT 15 --num-lags 5 --kernel-width 0.5 --prob-zero-removal 0 --prob-remove-samples 0.0 --family gaussian --replicate 2 --ID 2
--lambda 0.01 --dT 15 --num-lags 5 --kernel-width 0.5 --prob-zero-removal 0 --prob-remove-samples 0.0 --family gaussian --replicate 3 --ID 3
--lambda 0.01 --dT 15 --num-lags 5 --kernel-width 0.5 --prob-zero-removal 0 --prob-remove-samples 0.0 --family gaussian --replicate 4 --ID 4
--lambda 0.01 --dT 15 --num-lags 5 --kernel-width 0.5 --prob-zero-removal 0 --prob-remove-samples 0.0 --family gaussian --replicate 5 --ID 5 \" > data/inputs/example/GSD/SINGE/hyperparameters.txt && ln -s data/outputs/example/GSD/SINGE/0/ out0 && octave -q --eval \"CSV = csvread('data/inputs/example/GSD/SINGE/ExpressionData0.csv'); X = sparse(CSV(2:end,1:end-1).'); ptime = CSV(2:end,end).'; Kp2.Kp = single(ptime); Kp2.sumKp = single(ptime*X.'); fullKp(1, 75) = Kp2; save('-v7','data/inputs/example/GSD/SINGE/ExpressionData0.mat', 'X', 'ptime', 'fullKp'); f = fopen('data/inputs/example/GSD/SINGE/ExpressionData0.csv'); gene_list = strsplit(fgetl(f), ',')(1:end-1).'; fclose(f); save('-v7','data/inputs/example/GSD/SINGE/GeneList0.mat', 'gene_list')\" && time -v -o data/outputs/example/GSD/SINGE/time0.txt /usr/local/SINGE/SINGE.sh /usr/local/MATLAB/MATLAB_Runtime/v94 standalone data/inputs/example/GSD/SINGE/ExpressionData0.mat data/inputs/example/GSD/SINGE/GeneList0.mat out0 data/inputs/example/GSD/SINGE/hyperparameters.txt "' returned non-zero exit status 2.
(mmdet)

```

**Comment by yarkable** [comment]
It seems the cause is my machine. When I use another machine to install this, everything is OK. So I close this issue.
